// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_mvvm_samples/test/features/posts/data/repositories/posts_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i7;
import 'package:flutter_mvvm_samples/core/env/base_env_model.dart' as _i2;
import 'package:flutter_mvvm_samples/core/network/base_api.dart' as _i3;
import 'package:flutter_mvvm_samples/shared/data/models/product_model.dart'
    as _i6;
import 'package:flutter_mvvm_samples/shared/data/services/api/posts_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseEnvModel_0 extends _i1.SmartFake implements _i2.BaseEnvModel {
  _FakeBaseEnvModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsService extends _i1.Mock implements _i4.PostsService {
  MockPostsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseEnvModel get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: _FakeBaseEnvModel_0(
          this,
          Invocation.getter(#env),
        ),
      ) as _i2.BaseEnvModel);

  @override
  _i5.Future<_i3.ApiResult<List<_i6.PostModel>>> fetchPosts({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPosts,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResult<List<_i6.PostModel>>>.value(
            _FakeApiResult_1<List<_i6.PostModel>>(
          this,
          Invocation.method(
            #fetchPosts,
            [],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<List<_i6.PostModel>>>);

  @override
  _i5.Future<_i3.ApiResult<T>> request<T>({
    required String? path,
    required _i3.BaseHttpMethod? method,
    Map<String, dynamic>? query,
    dynamic data,
    required _i3.FromJson<T>? fromJson,
    _i7.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #path: path,
            #method: method,
            #query: query,
            #data: data,
            #fromJson: fromJson,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResult<T>>.value(_FakeApiResult_1<T>(
          this,
          Invocation.method(
            #request,
            [],
            {
              #path: path,
              #method: method,
              #query: query,
              #data: data,
              #fromJson: fromJson,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<T>>);

  @override
  _i5.Future<_i3.ApiResult<List<T>>> requestList<T>({
    required String? path,
    required _i3.BaseHttpMethod? method,
    Map<String, dynamic>? query,
    dynamic data,
    required _i3.FromJson<T>? fromJson,
    _i7.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestList,
          [],
          {
            #path: path,
            #method: method,
            #query: query,
            #data: data,
            #fromJson: fromJson,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.ApiResult<List<T>>>.value(_FakeApiResult_1<List<T>>(
          this,
          Invocation.method(
            #requestList,
            [],
            {
              #path: path,
              #method: method,
              #query: query,
              #data: data,
              #fromJson: fromJson,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<List<T>>>);
}
