// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_mvvm_samples/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i7;
import 'package:flutter_mvvm_samples/core/env/base_env_model.dart' as _i2;
import 'package:flutter_mvvm_samples/core/env/env.dart' as _i9;
import 'package:flutter_mvvm_samples/core/network/base_api.dart' as _i3;
import 'package:flutter_mvvm_samples/shared/data/models/login_response.dart'
    as _i6;
import 'package:flutter_mvvm_samples/shared/data/services/api/auth_service.dart'
    as _i4;
import 'package:flutter_mvvm_samples/shared/data/services/local/shared_preferences_service.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseEnvModel_0 extends _i1.SmartFake implements _i2.BaseEnvModel {
  _FakeBaseEnvModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseEnvModel get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: _FakeBaseEnvModel_0(
          this,
          Invocation.getter(#env),
        ),
      ) as _i2.BaseEnvModel);

  @override
  _i5.Future<_i3.ApiResult<_i6.LoginResponse>> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResult<_i6.LoginResponse>>.value(
            _FakeApiResult_1<_i6.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<_i6.LoginResponse>>);

  @override
  _i5.Future<_i3.ApiResult<_i6.LoginResponse>> refreshToken(
          {required String? refreshToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
          {#refreshToken: refreshToken},
        ),
        returnValue: _i5.Future<_i3.ApiResult<_i6.LoginResponse>>.value(
            _FakeApiResult_1<_i6.LoginResponse>(
          this,
          Invocation.method(
            #refreshToken,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<_i6.LoginResponse>>);

  @override
  _i5.Future<_i3.ApiResult<T>> request<T>({
    required String? path,
    required _i3.BaseHttpMethod? method,
    Map<String, dynamic>? query,
    dynamic data,
    required _i3.FromJson<T>? fromJson,
    _i7.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #path: path,
            #method: method,
            #query: query,
            #data: data,
            #fromJson: fromJson,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResult<T>>.value(_FakeApiResult_1<T>(
          this,
          Invocation.method(
            #request,
            [],
            {
              #path: path,
              #method: method,
              #query: query,
              #data: data,
              #fromJson: fromJson,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<T>>);

  @override
  _i5.Future<_i3.ApiResult<List<T>>> requestList<T>({
    required String? path,
    required _i3.BaseHttpMethod? method,
    Map<String, dynamic>? query,
    dynamic data,
    required _i3.FromJson<T>? fromJson,
    _i7.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestList,
          [],
          {
            #path: path,
            #method: method,
            #query: query,
            #data: data,
            #fromJson: fromJson,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.ApiResult<List<T>>>.value(_FakeApiResult_1<List<T>>(
          this,
          Invocation.method(
            #requestList,
            [],
            {
              #path: path,
              #method: method,
              #query: query,
              #data: data,
              #fromJson: fromJson,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<List<T>>>);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i8.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> getBool(
    _i8.PrefKey? key, {
    bool? defaultValue = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setBool(
    _i8.PrefKey? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> getString(_i8.PrefKey? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> setString(
    _i8.PrefKey? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int?> getInt(_i8.PrefKey? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<bool> setInt(
    _i8.PrefKey? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(_i8.PrefKey? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [BaseEnvModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseEnvModel extends _i1.Mock implements _i2.BaseEnvModel {
  MockBaseEnvModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Env get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: _i9.Env.staging,
      ) as _i9.Env);

  @override
  String get appIcon => (super.noSuchMethod(
        Invocation.getter(#appIcon),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#appIcon),
        ),
      ) as String);

  @override
  String get apiHost => (super.noSuchMethod(
        Invocation.getter(#apiHost),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#apiHost),
        ),
      ) as String);

  @override
  bool get enableCrashlytics => (super.noSuchMethod(
        Invocation.getter(#enableCrashlytics),
        returnValue: false,
      ) as bool);
}
