// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_mvvm_samples/test/features/auth/login/ui/viewmodel/login_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_mvvm_samples/shared/data/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthStatus_0 extends _i1.SmartFake implements _i2.AuthStatus {
  _FakeAuthStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.AuthStatus> get currentAuthStatus => (super.noSuchMethod(
        Invocation.getter(#currentAuthStatus),
        returnValue: _i3.Future<_i2.AuthStatus>.value(_FakeAuthStatus_0(
          this,
          Invocation.getter(#currentAuthStatus),
        )),
      ) as _i3.Future<_i2.AuthStatus>);

  @override
  _i3.Future<_i2.AuthStatus?> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i3.Future<_i2.AuthStatus?>.value(),
      ) as _i3.Future<_i2.AuthStatus?>);

  @override
  _i3.Future<_i2.AuthStatus> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<_i2.AuthStatus>.value(_FakeAuthStatus_0(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i3.Future<_i2.AuthStatus>);

  @override
  _i3.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
